In [1]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv(r"C:\Users\Owner\Desktop\대학\cct S1\strategic thinking\CA1\BER_2022_2024.csv")

C:\Users\Owner\AppData\Local\Temp\ipykernel_14404\510264700.py:1: DtypeWarning: Columns (0: CHPSystemTypeDescription, 1: FirstEnerConsumedComment, 2: SecondEnergyTypeId, 3: SecondEnerConsumedComment, 4: SecondEnerConsumedCO2EmissionFactor, 5: ThirdEnergyTypeId, 6: ThirdEnerProdComment, 7: ThirdPercentageHeat, 8: SolarSpaceHeatingSystem, 9: FirstWallArea, 10: FirstWallUValue, 11: FirstWallAgeBandId, 12: FirstWallTypeId, 13: SecondWallArea, 14: SecondWallUValue, 15: SecondWallAgeBandId, 16: SecondWallTypeId, 17: ThirdWallArea, 18: ThirdWallUValue, 19: RenewPrimaryEnergy3, 20: RenewPrimaryEPTot) have mixed types. Specify dtype option on import or set low_memory=False.
  df=pd.read_csv(r"C:\Users\Owner\Desktop\대학\cct S1\strategic thinking\CA1\BER_2022_2024.csv")

In [3]:
df['CountyName'].unique()
#co. dublin과 세부적으로 나눠진 더블린
#cork city, limerick city-> co.limerick, waterford city ->co. waterford
# 아니면 그냥 더블린만 해도 될 듯? co. dublin : 22883 이고 나눠진 게 66124야. 이정도면 충분할 듯한데
#

<StringArray>
[ 'Co. Waterford',   'Co. Limerick',       'Dublin 7',       'Co. Cork',
      'Co. Kerry',      'Dublin 10',      'Dublin 20',      'Dublin 22',
       'Dublin 6',       'Dublin 1',       'Dublin 5',      'Dublin 24',
       'Dublin 9',     'Co. Dublin',       'Dublin 8',    'Co. Donegal',
      'Dublin 17',    'Co. Kildare',       'Co. Mayo',   'Co. Kilkenny',
      'Dublin 18',  'Co. Roscommon',      'Dublin 13',    'Galway City',
  'Limerick City',     'Co. Carlow',      'Co. Louth',       'Dublin 4',
 'Waterford City',  'Co. Westmeath',      'Dublin 15',      'Co. Cavan',
     'Co. Galway',      'Co. Meath',    'Co. Wicklow',      'Dublin 14',
    'Co. Wexford',      'Dublin 12',      'Dublin 16',  'Co. Tipperary',
    'Co. Leitrim',       'Dublin 3',      'Dublin 11',      'Co. Sligo',
   'Co. Monaghan',      'Co. Clare',      'Co. Laois',       'Dublin 2',
     'Co. Offaly',      'Dublin 6W',   'Co. Longford',      'Cork City']
Length: 52, dtype: str

In [4]:
df['CountyName'].value_counts()

CountyName
Co. Cork          27730
Co. Dublin        22883
Co. Kildare       14666
Co. Meath         12089
Co. Wicklow       11197
Co. Galway         9432
Co. Wexford        9088
Co. Louth          7674
Co. Tipperary      7263
Co. Donegal        7191
Dublin 18          7182
Co. Kerry          7096
Co. Mayo           6559
Dublin 15          6544
Dublin 24          5475
Co. Clare          5447
Co. Westmeath      5069
Limerick City      4918
Co. Limerick       4845
Co. Laois          4594
Galway City        4490
Co. Kilkenny       4226
Dublin 8           4149
Co. Waterford      4102
Co. Sligo          3894
Dublin 12          3838
Co. Offaly         3650
Co. Roscommon      3468
Dublin 9           3432
Co. Cavan          3402
Dublin 11          3329
Waterford City     3237
Dublin 7           3167
Co. Carlow         3092
Dublin 22          3024
Dublin 14          2922
Dublin 16          2916
Co. Monaghan       2620
Dublin 13          2505
Dublin 4           2484
Dublin 1           2422
Dublin 3           2120
Dublin 5           2082
Dublin 6           1995
Co. Leitrim        1939
Co. Longford       1875
Dublin 20          1508
Dublin 6W          1338
Dublin 17          1236
Dublin 10          1234
Dublin 2           1222
Cork City           667
Name: count, dtype: int64

In [5]:
df.head()

,CountyName,DwellingTypeDescr,Year_of_Construction,TypeofRating,EnergyRating,BerRating,GroundFloorArea(sq m),UValueWall,UValueRoof,UValueFloor,...,PumpsFansPrimaryEnergy,LightingPrimaryEnergy,CoolingPrimaryEnergy,CHPInputPrimaryEnergy,CHPElecOutputPrimaryEnergy,RenewPrimaryEnergy1,RenewPrimaryEnergy2,RenewPrimaryEnergy3,RenewPrimaryEPTot,Unnamed: 252
0,Co. Waterford,Semi-detached house,1994,Existing,B2,111.00,45.57,0.55,0.12,0.47,...,1225.30,271.87,NaN,0.0,0.0,0.0,0.0,0,9260.34,NaN
1,Co. Limerick,Detached house,1998,Existing,E1,325.56,104.22,0.55,0.29,0.44,...,670.36,576.52,NaN,0.0,0.0,0.0,0.0,0,33930.0,NaN
2,Co. Waterford,Semi-detached house,1994,Existing,B2,111.00,45.57,0.55,0.12,0.47,...,1225.30,271.87,NaN,0.0,0.0,0.0,0.0,0,9260.34,NaN
3,Co. Waterford,Semi-detached house,1994,Existing,B2,110.80,45.57,0.55,0.12,0.47,...,1225.30,271.87,NaN,0.0,0.0,0.0,0.0,0,9234.74,NaN
4,Co. Waterford,Semi-detached house,1994,Existing,B2,110.80,45.57,0.55,0.12,0.47,...,1225.30,271.87,NaN,0.0,0.0,0.0,0.0,0,9234.74,NaN

In [6]:
df.shape

(274527, 253)

In [7]:

df.describe()

,Year_of_Construction,BerRating,GroundFloorArea(sq m),UValueWall,UValueRoof,UValueFloor,UValueWindow,UvalueDoor,WallArea,RoofArea,...,WHMainPrimaryEnergy,WHSecPrimaryEnergy,PumpsFansPrimaryEnergy,LightingPrimaryEnergy,CoolingPrimaryEnergy,CHPInputPrimaryEnergy,CHPElecOutputPrimaryEnergy,RenewPrimaryEnergy1,RenewPrimaryEnergy2,Unnamed: 252
count,274527.000000,274527.000000,274527.000000,274527.000000,274527.000000,274527.000000,274527.000000,274527.000000,274527.000000,274527.000000,...,274523.000000,274523.000000,274523.000000,274517.000000,249507.000000,274523.000000,274523.000000,274523.000000,274523.000000,3.000000
mean,1990.232687,158.846892,124.478599,0.564186,0.334929,0.367028,2.156166,2.037384,101.630115,74.920549,...,3376.683587,366.886405,898.418473,580.739670,0.172844,0.131579,0.046801,0.008415,0.612229,1.000000
std,35.606069,136.418803,68.040247,0.513615,0.469544,0.257741,0.867647,1.080630,63.660233,56.680918,...,1696.993323,764.106572,710.585565,269.805827,8.185545,35.089704,11.632518,4.408822,149.383867,1.732051
min,1760.000000,-472.990000,8.004000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-844.350000,-98.780000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1977.000000,48.100000,80.400000,0.210000,0.130000,0.140000,1.310000,1.360000,53.340000,43.580000,...,2183.040000,0.000000,306.250000,419.470000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,2002.000000,140.940000,108.200000,0.370000,0.190000,0.370000,2.200000,2.570000,92.630000,62.050000,...,3044.570000,0.000000,684.720000,526.650000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,2020.000000,209.430000,148.350000,0.600000,0.360000,0.570000,2.800000,3.000000,130.970000,100.340000,...,4222.985000,0.000000,1463.185000,674.980000,0.000000,0.000000,0.000000,0.000000,0.000000,1.500000
max,2025.000000,2607.450000,1190.840000,3.580000,7.000000,2.100000,8.340000,7.000000,1265.860000,866.460000,...,36081.800000,14010.100000,19612.200000,6072.490000,1492.470000,10892.800000,3770.880000,2310.000000,45424.789000,3.000000

In [8]:
df['DateOfAssessment'].isnull().sum()

np.int64(0)

In [9]:
keep_cols=["CountyName",
    "DateOfAssessment",
    "DwellingTypeDescr",
    "Year_of_Construction",
    "NoStoreys",
    "GroundFloorArea(sq m)",

    # 건물 외피 / 단열
    "UValueWall",
    "UValueRoof",
    "UValueFloor",
    "UValueWindow",
    "UvalueDoor",
    "WallArea",
    "RoofArea",
    "FloorArea",
    "WindowArea",
    "DoorArea",

    # 에너지 성능
    "EnergyRating",
    "BerRating",
    "CO2Rating",

    # 난방 / 온수
    "MainSpaceHeatingFuel",
    "MainWaterHeatingFuel",
    "HSMainSystemEfficiency",

    # 전력 사용
    "ElectricityConsumption", #제거후보

    # 태양광 자원
    "AnnualSolarRadiation", #제거 -> pvgis 사용

    # 기존 Solar PV
    "IsSolarPVBatteryPresent", #의미 확인
    "SolarBatteryCapacity", # 유지 -> 대부분 배터리 없고 일부만 실제 배터리 용량 가짐(0=! 결측)
    "SolarPVEnergyOutput"] #유지 -> 대부분 pv 발전량 0. 일부 집이 실제 pv 관련 값 있음 (0=! 결측) 
    #왜냐하면 단순한 Yes/No가 아니라 PV 시스템의 에너지 출력값으로 보이는 연속형 데이터이기 때문이야.그래서 나중에 이런 분석이 가능해져."아일랜드 주택의 어떤 특성이 PV 발전량에 영향을 미치는가?"그리고 그 결과를 경제성 모델과 연결할 수 있어.

In [10]:
df[keep_cols].isnull().sum()

CountyName                      0
DateOfAssessment                0
DwellingTypeDescr               0
Year_of_Construction            0
NoStoreys                       0
GroundFloorArea(sq m)           0
UValueWall                      0
UValueRoof                      0
UValueFloor                     0
UValueWindow                    0
UvalueDoor                      0
WallArea                        0
RoofArea                        0
FloorArea                       0
WindowArea                      0
DoorArea                        0
EnergyRating                    0
BerRating                       0
CO2Rating                       0
MainSpaceHeatingFuel         7638
MainWaterHeatingFuel         7638
HSMainSystemEfficiency       7638
ElectricityConsumption     265200
AnnualSolarRadiation       265200
IsSolarPVBatteryPresent         2
SolarBatteryCapacity            2
SolarPVEnergyOutput             7
dtype: int64

MainSpaceHeatingFuel               7638
MainWaterHeatingFuel               7638
HSMainSystemEfficiency             7638
ElectricityConsumption           265200 
AnnualSolarRadiation             265200
FirstSolarPVNoPanels             274527
FirstSolarPVPeakPowerPerPanel    274527
FirstSolarPVOrientation          274527
FirstSolarPVTilt                 274527
FirstSolarPVOvershading          274527
IsSolarPVBatteryPresent               2
SolarBatteryCapacity                  2
SolarPVEnergyOutput                   7

In [11]:
df['DwellingTypeDescr'].unique()

<StringArray>
[   'Semi-detached house',         'Detached house',      'Mid-terrace house',
 'Ground-floor apartment',             'Maisonette',    'Top-floor apartment',
    'Mid-floor apartment',   'End of terrace house',      'Basement Dwelling',
              'Apartment']
Length: 10, dtype: str

In [12]:
cols = [
    "IsSolarPVBatteryPresent",
    "SolarBatteryCapacity"
]

for col in cols:
    print("\n==============================")
    print(col)
    print("결측:", df[col].isna().sum())
    print("고유값:", df[col].nunique(dropna=True))
    print(df[col].value_counts(dropna=False).head(15))

==============================
IsSolarPVBatteryPresent
결측: 2
고유값: 6
IsSolarPVBatteryPresent
0.00       274520
NaN             2
3430.00         1
7326.00         1
5358.00         1
3716.44         1
3953.94         1
Name: count, dtype: int64

==============================
SolarBatteryCapacity
결측: 2
고유값: 223
SolarBatteryCapacity
0.00       274173
3512.00        14
4215.00         9
1675.00         8
4263.70         7
1078.00         6
2842.46         6
2810.00         5
3553.08         5
3737.52         5
3553.00         5
4117.00         4
3695.00         4
5172.00         4
2010.00         4
Name: count, dtype: int64

In [ ]:
cols = [
   
    "SolarPVEnergyOutput",
    "ElectricityConsumption"
    
]

for col in cols:
    print("\n==============================")
    print(col)
    print("결측:", df[col].isna().sum())
    print("고유값:", df[col].nunique(dropna=True))
    print(df[col].value_counts(dropna=False).head(15))

==============================
SolarPVEnergyOutput
결측: 7
고유값: 12858
SolarPVEnergyOutput
0.00       219279
3267.20       280
653.44        271
66.00         252
952.74        215
327.00        211
86.67         210
163.49        203
3512.24       200
3436.80       198
3308.04       191
3694.56       189
980.16        188
4214.69       169
188.00        163
Name: count, dtype: int64

==============================
ElectricityConsumption
결측: 265200
고유값: 2
ElectricityConsumption
NaN     265200
75.0      9047
0.0        280
Name: count, dtype: int64

==============================
AnnualSolarRadiation
결측: 265200
고유값: 120
AnnualSolarRadiation
NaN       265200
1074.0      2674
1021.0      2566
1072.0      1245
1005.0      1244
886.0        747
837.0        259
736.0         92
1036.0        52
1027.0        47
644.0         46
956.0         28
1073.0        22
1024.0        15
773.0         14
Name: count, dtype: int64

In [15]:
cols = [
   

    "AnnualSolarRadiation"
    
]

for col in cols:
    print("\n==============================")
    print(col)
    print("결측:", df[col].isna().sum())
    print("고유값:", df[col].nunique(dropna=True))
    print(df[col].value_counts(dropna=False).head(15))

==============================
AnnualSolarRadiation
결측: 265200
고유값: 120
AnnualSolarRadiation
NaN       265200
1074.0      2674
1021.0      2566
1072.0      1245
1005.0      1244
886.0        747
837.0        259
736.0         92
1036.0        52
1027.0        47
644.0         46
956.0         28
1073.0        22
1024.0        15
773.0         14
Name: count, dtype: int64